# Generated by Django 4.2.3 on 2023-08-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.TextField()),
                ('seria', models.TextField()),
                ('model', models.TextField()),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
            ],
        ),
    ]
