# Generated by Django 4.2.3 on 2023-08-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('img_address', models.TextField()),
                ('place', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'News',
            },
        ),
        migrations.AlterModelTable(
            name='car',
            table='Cars',
        ),
    ]
