# Generated by Django 4.2.3 on 2023-08-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_alter_car_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.TextField()),
                ('name', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Requests',
            },
        ),
    ]
