# Generated by Django 4.2.3 on 2023-10-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='seria',
            new_name='generation',
        ),
        migrations.AddField(
            model_name='car',
            name='acceleration_0_100',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.TextField(default='Белый'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='engine_capacity',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='engine_power_hp',
            field=models.IntegerField(default=330),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.TextField(default='Автоматическая'),
            preserve_default=False,
        ),
    ]
