# Generated by Django 4.2.3 on 2023-10-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_seria_car_generation_car_acceleration_0_100_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.TextField(default='10 000 000'),
            preserve_default=False,
        ),
    ]
