# Generated by Django 4.2.3 on 2023-10-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='img_addresses',
            field=models.TextField(default='car3'),
            preserve_default=False,
        ),
    ]
