# Generated by Django 4.2.3 on 2024-02-24 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_car_img_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='comment',
            field=models.TextField(default='Нет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
