# Generated by Django 4.2.3 on 2024-02-24 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_request_comment_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
