# Generated by Django 4.2.3 on 2024-06-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_request_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='drive',
            field=models.TextField(default='No'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='engine_cylinder',
            field=models.TextField(default='No'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='engine_power_kw',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='engine_type',
            field=models.TextField(default='No'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='max_speed',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='email',
            field=models.TextField(default='No'),
            preserve_default=False,
        ),
    ]
