# Generated by Django 4.2.3 on 2024-08-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_car_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='preview',
            field=models.TextField(default='car1'),
            preserve_default=False,
        ),
    ]
